add Terminology section
solid/webid-profile pull request #103
Opened 2023-09-05 08:30 UTC by VirginiaBalseiro

Closes #21 

Also removed some minor "to-do" comments that have been addressed.

2023-09-05 14:33 UTC, TallTed requested changes

2023-09-05 14:33 UTC, TallTed commented on index.html
> +                    A <dfn>Solid Profile </dfn> is the representation of a social agent's identity within the Solid ecosystem, which is used to describe their persona, preferences, abilities, affilia
```suggestion
                    A <dfn>Solid profile</dfn> is a representation of a social agent's identity within the Solid ecosystem, which can be used to describe their persona, preferences, abilities, affiliations, social activities and relationships, characteristics, and digital presence, as well as to aid in the discovery of storage and location of specific data.
```

2023-09-05 14:33 UTC, TallTed commented on index.html
> +                    <dfn id="extended-profile">Extended Profile</dfn>
```suggestion
                    <dfn id="extended-profile">Extended Solid Profile</dfn>
```

2023-09-05 14:33 UTC, TallTed commented on index.html
> +                    A <dfn>preferences document</dfn>  is a specific resource intended to store data which helps authorized applications accommodate the user's preferences, such as settings, personal
I forget the dfn syntax that lets you have multiple spellings/phrasings, so `extended profile` may be treated as equivalent to `extended Solid profile`... which I think would be optimal.
```suggestion
                    An <dfn>extended Solid profile</dfn> is an additional profile document that provides supplemental description to a Solid profile to help distribute and manage information about a WebID for use in different circumstances. Extended profile documents can be used for various purposes, such as organizing information or limiting access to certain data.
                  </dd>
                </dl>

                <dl>
                  <dt
                    about="#preferences-document"
                    property="skos:prefLabel"
                    typeof="skos:Concept"
                  >
                    <dfn id="preferences-document">Preferences Document</dfn>
                  </dt>
                  <dd about="#preferences-document" property="skos:definition">
                    A <dfn>preferences document</dfn> is a specific resource intended to store data which helps authorized applications accommodate the user's preferences, such as settings, personalization details, and pointers to the user's private data.
```

2023-09-05 15:05 UTC, elf-pavlik commented on index.html
> +                    A <dfn>Solid profile</dfn> is a representation of a social agent's identity within the Solid ecosystem, which can be used to describe their persona, preferences, abilities, affili
```suggestion
                    A <dfn>Solid profile</dfn> is a description of a social agent's identity within the Solid ecosystem, which can be used to describe their persona, preferences, abilities, affiliations, social activities and relationships, characteristics, and digital presence, as well as to aid in the discovery of storage and location of specific data.
```

I think representation might suggest a specific serialization / media-type

2023-09-05 15:18 UTC, timbl approved these changes
LGTM

2023-09-05 17:25 UTC, TallTed approved these changes

2023-09-06 07:39 UTC, csarven approved these changes
Good stuff. I don't have anything to add/subtract (right now :)). PR looks like ready to go.

2023-09-06 07:41 UTC, merged