Update for publishing CG-DRAFT
solid/webid-profile pull request #117
Opened 2024-05-28 09:30 UTC by csarven

Updates Solid WebID Profile, Version 1.0.0. Publishes:

* This version: https://github.com/solid/webid-profile/ (update)

"This version" is a request to be published as a CG-DRAFT report of the Solid CG.

---

Solid WebID Profile has only one document type at the moment. Whereas Solid Protocol, Solid Notifications Protocol, Web Access Control have separate documents for "published" and "editor's drafts".

If the group wants to do something similar, i.e., https://github.com/solid/webid-profile/ as an editor's draft, and https://solidproject.org/TR/webid-profile as a CG-DRAFT, we can do that too.

2024-05-28 11:01 UTC, elf-pavlik commented
I think 1.0.0 sends misleading signal about stability of this proposal. Probably should be 0.1

2024-05-28 11:02 UTC, jeff-zucker commented
I object to this draft being published without my input.  If you publish it now, please remove my name from the editor and authors draft and note my official objection.  I can submit issues and PRs later this week.

2024-05-28 11:33 UTC, jeff-zucker requested changes
I object to this PR.  I will submit suggested changes within a week.

2024-05-28 11:44 UTC, csarven commented
>I think 1.0.0 sends misleading signal about stability of this proposal. Probably should be 0.1

I think 0.1 would be an utterly misleading signal about its stability considering the fact that:
* the described work goes about a decade https://github.com/solid/solid-spec/blob/master/README.md#identity  (if not generally longer)
* is "widely" implemented.

The document is currently versioned 1.0.0, and has been for a long time, which was also based on discussions in the CG (please let me know if I need to pull decisions... but it'd save me a minute or two if I didn't have to bother).

I see nothing wrong with CG-DRAFT v1.0.0. It is literally a "draft". It changes absolutely nothing concrete about its implementability going from the current v1.0.0 to CG DRAFT v1.0.0.

If the versioning information tagged on is in any way a "misleading signal", then an alternative proposal is to publish it without the versioning information, so just "CG-DRAFT".

If you feel that this document is inadequate for a CG-DRAFT, then I'd like to request a clear criteria on what should constitute CG-DRAFT. Here is one stub towards such criteria for the CG document: https://github.com/solid/specification/issues/373 . Once something like that is in place, we can verify all proposals for a CG-DRAFT publication in the same way.

2024-05-28 11:50 UTC, csarven commented
>I object to this PR. I will submit suggested changes within a week.

Looking forward to change suggestions. I don't see why they can't be integrated as long as there is consensus. That aside, in the absence of change suggestions, is there something concrete or conceptual or process related objection?

2024-05-28 12:32 UTC, elf-pavlik commented
> I see nothing wrong with CG-DRAFT v1.0.0. It is literally a "draft". It changes absolutely nothing concrete about its implementability going from the current v1.0.0 to CG DRAFT v1.0.0.

What semantic version number do you plan to use 5 versions down the road? If two of those versions have breaking changes will you have CG-DRAFT v3.0.0 ?

2024-05-28 12:41 UTC, csarven commented
>What semantic version number do you plan to use 5 versions down the road? If two of those versions have breaking changes will you have CG-DRAFT v3.0.0 ?

I think that's answered by following Semantic Versioning? Again, if we don't want the version number, we can discuss dropping them altogether for this report; for some reports, or; for all reports.

2024-05-28 12:52 UTC, csarven commented
>Nope, I just want an opportunity to suggest some changes. I mentioned them in https://github.com/solid/webid-profile/pull/116 

Right, again, I see no reason not to get any changes in provided there is consensus. At the same time, we do need to weigh in on whether something is a blocker and what consensus would unblock. For example, CG-DRAFT (with whatever version or no version) can be published and as soon as we have an agreed change, we can update the CG-DRAFT.

>In terms of process I suggest that all future decisions about the WebID Profile Document take pace in STMs of the CG devoted to that topic which will make it easier to follow this document without having to disentangle it from general CG topics which, I simply do not have the time to do.

I think that's a useful thing to raise to the whole CG.

>I'd also like some clarity on the difference between the ED-Draft and the CG-Draft.

Again, W3C is not entirely clear on this and I've been requesting feedback on how W3C Team should consider the fact that CGs do need to use an ED of sorts to take care of WIP stuff, alongside make CG-DRAFT releases.

So, as I understand it, as it stands, what an ED may be to us (CG) internally for day to day stuff / changes, shouldn't have "W3C" branding / naming / styling / statuses / rights etc. Everything else can remain the same. It is only the CG-DRAFT that can have some "official" W3C stuff in the document. This is part of the reason why we are trying to transition to CG-DRAFT reports so that we can rightfully say that they are CG reports.

2024-05-29 14:21 UTC, michielbdejong approved these changes

2024-05-29 15:39 UTC, timbl approved these changes
LGTM

2024-05-29 15:43 UTC, timbl requested changes
Wait -  we lost the version number.  There must  be  versionnumber.  I suggest 1.1

2024-05-29 15:49 UTC, VirginiaBalseiro commented
> Wait - we lost the version number. There must be versionnumber. I suggest 1.1

@timbl we have version number, see: https://htmlpreview.github.io/?https://github.com/solid/webid-profile/blob/54e7242b51646e8ee68f69e09dbdfc9e1e0fde10/index.html

> Version
> 1.0.0

2024-06-04 20:53 UTC, jeff-zucker approved these changes
Withdrawing my objection to publishing, this since most of the things I would have changed hinge on issues we'll be discussing in the special topics.

2024-06-05 08:54 UTC, merged