simplify the pointer to the community as implemented in code
solid/webid-profile pull request #17
Opened 2022-06-21 21:17 UTC by timbl

There is a direct pointer from profile *or oreferences) to a community or communities.

2022-06-21 22:40 UTC, jeff-zucker approved these changes
LGTM

2022-06-22 06:09 UTC, VirginiaBalseiro approved these changes

2022-06-27 10:45 UTC, timea-solid requested changes

2022-06-27 10:45 UTC, timea-solid commented on notes/pre-final-draft.md
> +is placed in either the user's the private preferences or public profile.  The `org` node's URI is the WebID URI of the project, etc.
```suggestion
is placed in either the user's private preferences or public profile.  The `org` node's URI is the WebID URI of the project, etc.
```

2022-06-27 10:47 UTC, timea-solid commented
![Screenshot 2022-06-27 at 12 44 17](https://user-images.githubusercontent.com/4144203/175924457-641751b7-1daf-42ab-b63c-aac6260b0fe5.png)
Please also remove extra arrow in diagram

2022-06-28 07:51 UTC, timea-solid approved these changes

2022-06-28 09:46 UTC, merged